name: Forward Dependabot updates to template

on:
  push:
    branches: [ main ]   # <-- change if your default branch is not 'main'

permissions:
  contents: read

jobs:
  forward:
    name: Forward to bogdanctx/oop-template
    runs-on: ubuntu-latest

    env:
      TEMPLATE_REPO: bogdanctx/oop-template
      TEMPLATE_REF: main
      PR_BRANCH_PREFIX: chore/deps-forward
      # Whitelist patterns that are allowed to be forwarded upstream:
      # add/adjust as needed for your project
      ALLOWED_GLOBS: |
        .github/workflows/**/*.yml
        .github/workflows/**/*.yaml
        .github/actions/**/*
        package.json
        package-lock.json
        pnpm-lock.yaml
        yarn.lock
        Pipfile
        Pipfile.lock
        requirements*.txt
        pyproject.toml
        poetry.lock
        CMakeLists.txt
        cmake/**/*.cmake
        vcpkg-configuration.json
        conanfile.*
        Makefile
        Dockerfile
        .dockerignore

    steps:
      - name: Checkout dependencies repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed files in this push
        id: diff
        run: |
          set -e
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # initial push: compare with first parent if available
            git rev-list --max-parents=0 HEAD | tail -n1 > base.txt
            BEFORE=$(cat base.txt)
          fi

          git diff --name-only --diff-filter=ACDMRT $BEFORE $AFTER > changed.txt
          echo "Changed files:"
          cat changed.txt || true

          # Filter by allowed globs
          awk 'NF' <<'GLOBS' > globs.txt
          $ALLOWED_GLOBS
GLOBS

          rm -f forward.txt
          touch forward.txt
          while read -r file; do
            while read -r glob; do
              # Use bash's [[ ]] glob match
              if [[ "$file" == $glob ]]; then
                echo "$file" >> forward.txt
                break
              fi
            done < globs.txt
          done < changed.txt

          sort -u forward.txt -o forward.txt
          echo "Files to forward:"
          cat forward.txt || true

          COUNT=$(wc -l < forward.txt | tr -d ' ')
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Stop if nothing to forward
        if: steps.diff.outputs.count == '0'
        run: echo "No dependency-related changes to forward."

      - name: Checkout template repo (target)
        if: steps.diff.outputs.count != '0'
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATE_REPO }}
          ref: ${{ env.TEMPLATE_REF }}
          path: template
          token: ${{ secrets.TEMPLATE_TOKEN }}

      - name: Copy changed files into template working tree
        if: steps.diff.outputs.count != '0'
        run: |
          set -e
          while read -r f; do
            # ensure destination directory exists
            mkdir -p "template/$(dirname "$f")"
            cp -R --parents "$f" template/ 2>/dev/null || cp -R "$f" "template/$f"
          done < forward.txt

          # Show what will change upstream
          cd template
          if git diff --quiet; then
            echo "No actual diffs in template after copying (maybe already up to date)."
            exit 0
          fi
          git status --porcelain
          cd -

      - name: Open PR into template
        if: steps.diff.outputs.count != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          path: template
          token: ${{ secrets.TEMPLATE_TOKEN }}
          branch: ${{ env.PR_BRANCH_PREFIX }}-${{ github.run_id }}
          base: ${{ env.TEMPLATE_REF }}
          commit-message: "chore(deps): forward dependency updates from ${{ github.repository }}@${{ github.sha }}"
          title: "chore(deps): forward dependency updates from ${{ github.repository }}"
          body: |
            This PR was opened automatically after dependency-related files changed in **${{ github.repository }}**.

            - Source push: ${{ github.sha }}
            - Forwarded files:
            ```
            ${{ steps.diff.outputs.count }} file(s)
            ```
          delete-branch: true
