name: Send updates to oop-template

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

env:
  TEMPLATE_OWNER: bogdanctx
  TEMPLATE_REPO: oop-template
  SOURCE_REPO: bogdanctx/oop-template-dependencies
  DEFAULT_BRANCH: main

jobs:
  sync:
    name: Compare & PR to template
    runs-on: ubuntu-latest

    steps:
      - name: Check required  secret
        env:
          HAS_TOKEN: ${{ secrets.TEMPLATE_REPO_TOKEN != '' }}
        run: |
          if [[ "${HAS_TOKEN}" != "true" ]]; then
            echo "::error::Secret TEMPLATE_REPO_TOKEN missing"
            exit 1
          fi
      
      - name: Checkout source (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Checkout template repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATE_OWNER }}/${{ env.TEMPLATE_REPO }}
          token: ${{ secrets.TEMPLATE_REPO_TOKEN }}
          path: template
          fetch-depth: 0

      - name: Sync .github/actions & .github/workflows
        id: sync_dirs
        shell: bash
        run: |
          set -euo pipefail
          
          echo "Using template base branch: ${DEFAULT_BRANCH}" >> "$GITHUB_STEP_SUMMARY"
          git -C template checkout main

          mkdir -p template/.github/actions
          mkdir -p template/.github/workflows

          rsync -a --delete \
            --include='.github/' \
            --exclude='.github/workflows/update-template.yml' \
            --exclude='.github/dependabot.yml' \
            --include='.github/actions/***' \
            --include='.github/workflows/***' \
            --exclude='*' \
            ./ template/

          if git -C template status --porcelain -- .github/actions .github/workflows | grep -q .; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"

            {
              echo "### Changes detected"
              echo
              echo '```dif'
              git -C template --no-pager diff -- .github/actions .github/workflows | sed -e 's/^/ /'
              echo '```'
            } >> "$GITHUB_STEP_SUMMARY"

            {
              echo "changed_files << EOF"
              git -C template --no-pager diff --name-status -- .github/actions .github/workflows .github/workflow
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected in .github/actions or .github/workflows." >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Create PR on template
        if: ${{ steps.sync_dirs.outputs.has_changes == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TEMPLATE_REPO_TOKEN }}
          path: template
          branch: sync/gha-from-dependencies
          base: ${{ env.DEFAULT_BRANCH }}
          commit-message: |
            chore: sync workflows from ${{ env.SOURCE_REPO }} @ ${{ github.sha }}
          titles: |
            Sync GitHub Actions from ${{ env.SOURCE_REPO }}
          body: |
            PR auto-generated in **${{ env.SOURCE_REPO }}** to sync:
            - `.github/actions`
            - `.github/workflows`
          
            ** Source commit:** `${{ github.sha }}`
            
            **Changed files:**
            ```
            ${{ steps.sync_dirs.outputs.changed_files }}
            ```

      - name: No-op when nothing changed
        if: ${{ steps.sync_dirs.outputs.has_changes == 'false' }}
        shell: bash
        run: echo "Nothing to PR."
